routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "Games\LimiteLimiteController@home")->name('home');
Route::post('/', "HomeController@setUsername")->name('set-username');

Route::get("/early-access", "HomeController@earlyAccess")->name("early-access");
Route::post("/early-access", "HomeController@checkEarlyAccessToken");

Route::namespace("Games\\")
    ->middleware('earlyAccess')
    ->group(function () {

        /**
         * ------------------------------------------------------
         *              Limit-Limit routes
         * ------------------------------------------------------
         *
         */
        Route::prefix("/limite-limite")
            ->name("limite-limite.")
            ->group(function () {

                Route::get("/", "LimiteLimiteController@home")->name('home');
                Route::post("/", "LimiteLimiteController@store")->name("store");
                Route::get("/create", "LimiteLimiteController@create")->name("create");
                Route::get("/{token}", "LimiteLimiteController@show")->name("show");
                Route::get("/{token?}/join", "LimiteLimiteController@join")->name("join");
                Route::post("/{token}/join", "LimiteLimiteController@joinRequest")->name("join-request");

            });

    });

app/Http/Controllers/Games/LimiteLimiteController.php
<?php

namespace App\Http\Controllers\Games;

use App\Http\Controllers\Api\Requester\DeckManagerRequesterAPI;
use App\Http\Controllers\Controller;
use App\Models\LimiteLimiteGame;
use App\Objects\Player;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Str;

class LimiteLimiteController extends Controller
{

    public function home()
    {

        return View::make('games.limite-limite.home')->with(['games' => LimiteLimiteGame::all()]);

    }

    public function create()
    {

        return View::make('games.limite-limite.create');

    }

    public function store(Request $request)
    {

        $rules = [
            "name" => "required|string",
        ];

        if(!session()->has("username"))
            $rules["username"] = "required|string";

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
            foreach ($validator->errors()->all() as $error)
                flash($error)->error();
        }

        $decks = [];
        if ($request->get("decks") !== null) {

            $decks = explode(" ", $request->get("decks"));
            $decks = DeckManagerRequesterAPI::getMultipleDecks($decks);

            $decks["responses"] = [];
            $decks["calls"] = [];


            foreach ($decks as $key => $deck) {

                if ($key !== "responses" && $key !== "calls") {

                    //Reduce CardCastGame API calls from two to one
                    if (($deck->response_count > 0) && ($deck->call_count > 0)) {

                        $cards = DeckManagerRequesterAPI::getAllDeckCards($deck->id);
                        $decks["responses"][$deck->id] = $cards->responses;
                        $decks["calls"][$deck->id] = $cards->calls;



                    }
                    else if ($deck->response_count > 0)
                        $decks["responses"][$deck->id] = DeckManagerRequesterAPI::getResponsesCardsFromDeck($deck->id);


                    else if ($deck->call_count > 0)
                        $decks["calls"][$deck->id] = DeckManagerRequesterAPI::getCallsCardsFromDeck($deck->id);

                    unset($decks[$key]);

                }
            }

        }

        if(!session()->has("username")){

            session()->put("username", $request->get("username"));
            $hostName = $request->get("username");

        }
        else
            $hostName = session()->get("username");

        $host = new Player($hostName, 0, false, 0, [], $decks["responses"], true);
        $host->shuffleDeck();
        $host->setIdentifier(0);

        if (session()->has("player_api_token"))
            session()->forget("player_api_token");

        session()->put("player_api_token", $host->getApiToken());

        $players = array();
        $players[$host->getApiToken()] = $host;

        $game = new LimiteLimiteGame();

        $game->token = utf8_encode(Str::random(16));
        $game->restart_token = utf8_encode(Str::random(16));
        $game->name = $request->get('name');
        $game->password = Hash::make($request->get('password'));
        $game->host = $host->getApiToken();
        $game->ident_index = 0;
        $game->options = $game->getDefaultOptions();
        $game->current_round = $game->generateCurrentRound($decks["calls"]);
        $game->last_round = $game->generateLastRound();
        $game->players = $players;
        $game->czard_index = 0;
        $game->calls_decks = $decks["calls"];
        $game->responses_decks = $decks["responses"];
        $game->active = 0;
        $game->created_at = Carbon::now();
        $game->updated_at = Carbon::now();

        $game->save();

        flash("Partie créée avec succès")->success();
        return Redirect::route("limite-limite.show", $game->token);

    }

    public function show(Request $request, string $token)
    {

        $game = LimiteLimiteGame::where('token', '=', $token)->first();
        if(!$game) {
            flash("Cette partie n'a pas pu être trouvée")->error();
            return Redirect::back();
        }

        $api_token = session()->get("player_api_token");

        if ($api_token == null || $game->getPlayer($api_token) === NULL) {
            flash("Vous ne pouvez pas accéder à cette partie")->warning();
            return Redirect::route('limite-limite.join', $token);
        }

        $data = [];
        $data["token"] = $token;
        $data["hasPlayed"] = !$game->isPlayerHandEmpty($api_token);
        $data["player_hand"] = [];

        return View::make("games.limite-limite.show")->with($data);

    }

    public function join(Request $request, $token = null){

        if($token === null){

            flash(trans("app.no_choosen_game"))->warning();
            return Redirect::route("limite-limite.hub");

        }

        $game = LimiteLimiteGame::where('token', '=', $token)->first();

        if(!$game) {
            flash("Cette partie n'a pas pu être trouvée")->error();
            return Redirect::back();
        }

        if(session()->has("player_api_token") && !$game->hasPassword()){

            if($game->getPlayer(session("player_api_token")) !== NULL){

                flash(trans("app.welcome_back"))->info();
                return Redirect::route("limite-limite.show", $token);

            }

            else {

                return $this->joinRequest($request, $token);

            }

        }

        $data = [];
        $data["game"] = $game;
        $data["token"] = $token;

        return View::make("games.limite-limite.join")->with($data);

    }

    public function joinRequest(Request $request, $token = null){

        $game = LimiteLimiteGame::where('token', '=', $token)->first();

        if(!$game) {
            flash("Cette partie n'a pas pu être trouvée")->error();
            return Redirect::back();
        }

        if(session()->has("player_api_token")){

            if($game->getPlayer(session("player_api_token")) !== NULL){

                flash(trans("app.welcome_back"))->info();
                return Redirect::route("limite-limite.show", $token);

            }

            else {

                return $this->enterGame($request, $game);

            }

        }

        $rules = [];
        $rules["username"] = "required";

        if($game->hasPassword())
            $rules["password"] = "required";


        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            foreach ($validator->errors()->all() as $error)
                flash($error)->error();

            return Redirect::back()->withInput(["username" => $request->get('username')]);
        }

        if(!Hash::check($request->get('password'), $game->password)){

            flash(trans("app.invalid_password"))->error();
            return Redirect::back()->withInput(["username" => $request->get('username')]);

        }

        return $this->enterGame($request, $game);

    }

    private function enterGame(Request $request, LimiteLimiteGame $game){

        $username = session()->has("username") ? session()->get('username') : $request->get('username');

        if($game->doesUsernameExist($username)){

            session()->forget("username");
            session()->put("username", $username);
            flash(trans("app.username_already_taken"))->error();
            return Redirect::back();

        }

        $player = new Player($username, 0, false, 0, [], $game->responses_decks, true);
        $player->shuffleDeck();

        if (session()->has("player_api_token"))
            session()->forget("player_api_token");

        session()->put("player_api_token", $player->getApiToken());
        session()->put("username", $player->name);

        $game->addPlayer($player);

        return Redirect::route("limite-limite.show", $game->token);
    }

}

resources/views/games/limite-limite/create.blade.php
@extends("layouts.master")

@section("title", trans("app.create_game"))

@section("content")

    <div class="content">

        <h3>Création de partie</h3>

        <form method="POST" action="{{ route("limite-limite.store") }}">

            <div class="form-group form-row">
                <div class="col col-md">
                    <label for="name">Nom de la partie :</label>
                    <input type="text" name="name" id="name" class="form-control">
                </div>

                @if(!session()->has("username"))
                    <div class="col col-md">
                        <label for="username">Pseudo :</label>
                        <input type="text" class="form-control" name="username" id="username"/>
                    </div>
                @endif

                <div class="col col-md">
                    <label for="lang">Langage de la partie :</label>
                    <select name="lang" id="lang" class="form-control">
                        <optgroup label="Langage de la partie">
                            <option value="fr"> &#127467;&#127479; Français</option>
                            <option value="us"> &#127482;&#127480; Anglais</option>
                        </optgroup>
                    </select>
                </div>
            </div>


            <div class="form-group">
                <label for="password">Mot de passe (Optionnel) :</label>
                <input type="text" name="password" id="password" class="form-control">
                <small class="form-text text-muted"><strong>Laissez ce champ vide pour créer une partie
                        publique</strong></small>
            </div>

            <div class="form-group form-row">
                <div class="col col-md mb-3">
                    <label for="max_players">Nombre de joueurs maximum :</label>
                    <input type="text" min="3" max="20" value="3" name="max_players" id="max_players"
                           class="form-control form-control-sm disabled" readonly>
                    <small class="form-text text-muted">Choisissez un nombre entre 3 et 20</small>
                </div>
                <div class="col col-md mb-3">
                    <label for="max_spectators">Nombre d'observateurs maximum :</label>
                    <input type="number" min="0" max="20" value="0" name="max_spectators" id="max_spectators"
                           class="form-control form-control-sm disabled" readonly>
                    <small class="form-text text-muted">Choisissez un nombre entre 0 et 20</small>
                </div>

                <div class="col col-md mb-3">
                    <label for="max_points">Nombre de points pour gagner :</label>
                    <input type="number" min="0" max="20" value="0" name="max_points" id="max_points"
                           class="form-control form-control-sm disabled" readonly>
                    <small class="form-text text-muted">Choisissez un nombre entre 0 et 20</small>
                </div>
            </div>

            <div class="form-group">
                <label for="decks">Deck(s) de jeu :</label>
                <input type="text" name="decks" id="decks" class="form-control">
                <small class="form-text text-muted">Entrez les codes Cardcast désirés, tous séparés par un
                    espace</small>
            </div>

            <!-- Options de membre connecté --
            <div class="form-group d-flex justify-content-center">
                <div class="col-12 col-lg-6 p-0">

                    !-- Is Player Offline --
                    <div class="connected-rules-offline text-muted">
                        Vous pouvez créer un compte et vous connecter afin de configurer et récupérer vos decks favoris.
                    </div>
                    --

                    !-- Is Player Online --
                    <hr>
                    <div id="favorite-decks">

                        <h6>Decks favoris :</h6>

                        <ul class="list-group">
                            <li class="list-group-item">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="EQSFS" id="EQSFS">
                                    <label class="form-check-label" for="EQSFS">Nom de pack random avec pour code EQSFS</label>
                                </div>
                            </li>
                            <li class="list-group-item">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="QGDSF" id="QGDSF">
                                    <label class="form-check-label" for="QGDSF">Nom de pack random avec pour code QGDSF</label>
                                </div>
                            </li>
                            <li class="list-group-item">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="HGSFS" id="HGSFS">
                                    <label class="form-check-label" for="HGSFS">Nom de pack random avec pour code HGSFS</label>
                                </div>
                            </li>
                            <li class="list-group-item">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="POFSI" id="POFSI">
                                    <label class="form-check-label" for="POFSI">Nom de pack random avec pour code POFSI</label>
                                </div>
                            </li>
                            <li class="list-group-item">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="DS4DS" id="DS4DS">
                                    <label class="form-check-label" for="DS4DS">Nom de pack random avec pour code DS4DS</label>
                                </div>
                            </li>

                            <li class="list-group-item">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="GDSFZ" id="GDSFZ">
                                    <label class="form-check-label" for="GDSFZ">Nom de pack random avec pour code GDSFZ</label>
                                </div>
                            </li>

                            <li class="list-group-item">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="6KIF7" id="6KIF7">
                                    <label class="form-check-label" for="6KIF7">Nom de pack random avec pour code 6KIF7</label>
                                </div>
                            </li>

                            <li class="list-group-item">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="WCO46" id="WCO46">
                                    <label class="form-check-label" for="WCO46">Nom de pack random avec pour code WCO46</label>
                                </div>
                            </li>
                        </ul>

                    </div>
                    --

                </div>
            </div>
            -->

            @csrf
            <button type="submit" id="submit-form-btn" class="btn btn-block btn-primary">Créer une nouvelle partie</button>

        </form>

    </div>

@endsection

resources/views/games/limite-limite/home.blade.php
@extends('layouts.master')

@section("container", "container-fluid")

@section('content')

    <!-- Page Content -->
    <div class="container-fluid">

        <h3>Bienvenue sur {{ app_name() }}</h3>

        <div class="row text-justify jumbotron mb-0 py-1 c-bg-squared">

        @foreach($games as $game)
            <!-- Partie créée -->
                <div class="col-lg-6 col-12 my-3">
                    <div class="card bg-secondary">

                        <div class="card-header row pb-2 mx-0">
                            <div class="col-8 px-0">{{ $game->name }}</div>
                            <div class="col-4 px-0 text-right">
                                @switch($game->getStatus())
                                    @case($game::STATUS_GAME_OVER)
                                        <i class="fas fa-circle text-danger"></i> {{ trans("app.game_over") }}
                                        @break
                                    @case($game::STATUS_PLAYING)
                                        <i class="fas fa-circle text-success"></i> {{ trans("app.playing") }}
                                        @break
                                    @default
                                        <i class="fas fa-circle text-warning"></i> {{ trans("app.error_happened") }}
                                        @break
                                @endswitch
                            </div>
                        </div>

                        <div class="card-body text-muted">
                            <table class="w-100">
                                <!-- Players, Spectators,  -->
                                <tr class="align-top">
                                    <td class="pb-3">
                                        <strong class="d-md-block">Joueurs</strong>
                                        <p>{{ $game->countPlayers() }}/20</p>
                                    </td>
                                    <td class="pb-3">
                                        <strong class="d-md-block">Spectateurs</strong>
                                        <p>{{ $game->countSpectators() }}/20</p>
                                    </td>
                                    <td class="pb-3 text-right"><strong>{{ $game->getOption("lang") }}</strong></td>
                                </tr>

                                <!-- Points Needed -->
                                <tr class="align-top">
                                    <td colspan="3"><strong>Score max : </strong>{{ $game->getOption("max_points") }}
                                    </td>
                                </tr>

                                <!-- Host Name -->
                                <tr class="align-top">
                                    <td colspan="3"><strong>Hôte : </strong>{{ $game->getHost()->name }}</td>
                                </tr>

                                <!-- Tags -->
                                <tr class="align-top">
                                    <td colspan="3" class="text-justify"><strong>Tags : </strong>{{ $game->getTags()  }}</td>
                                </tr>

                                <!-- Boutons -->
                                <tr class="align-middle">
                                    <td class="font-italic">
                                        <p class="d-none d-md-block m-0">Rejoindre en tant que :</p>
                                    </td>
                                    <td colspan="2" class="text-right">
                                        <span class="d-inline-block" data-toggle="tooltip" data-placement="top"
                                              title="Fonctionnalité à venir">
                                        <a class="btn btn-secondary disabled" type="button" disabled>Observateur</a>
                                    </span>
                                        <a href="{{ route("limite-limite.join", $game->token) }}" class="btn btn-primary">Joueur</a>
                                    </td>
                                </tr>
                            </table>
                        </div>

                    </div>
                </div>
            @endforeach

        </div>
    </div>

@endsection

resources/views/games/limite-limite/join.blade.php
@extends('layouts.master')

@section('title', 'Hub')

@section('content')

    <h1>Limite-Limite</h1>
    <h4>{{ $game->name }}</h4>

    <div class="row justify-content-center">
        <div class="col-8">
            <form action="{{ route('limite-limite.join-request', $token) }}" method="POST" style="margin-top: 40px">

                <input type="text" name="username" id="username"
                       class="form-control" placeholder="Choisir un nom d'utilisateur"
                        value="{{ session()->has("username") ? session()->get("username") : old("username") }}">

                @if($game->hasPassword())
                    <input type="password" name="password" class="form-control" placeholder="Entrez le mot de passe">
                @endif
                @csrf

                <input type="submit" class="btn btn-primary" value="Rejoindre"/>
            </form>
        </div>
    </div>

@endsection