routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "Games\LimiteLimiteController@home")->name('home');
Route::post('/', "HomeController@setUsername")->name('set-username');

Route::get("/early-access", "HomeController@earlyAccess")->name("early-access");
Route::post("/early-access", "HomeController@checkEarlyAccessToken");

Route::namespace("Games\\")
    ->middleware('earlyAccess')
    ->group(function () {

        /**
         * ------------------------------------------------------
         *              Limit-Limit routes
         * ------------------------------------------------------
         *
         */
        Route::prefix("/limite-limite")
            ->name("limite-limite.")
            ->group(function () {

                Route::get("/", "LimiteLimiteController@home")->name('home');
                Route::post("/", "LimiteLimiteController@store")->name("store");
                Route::get("/create", "LimiteLimiteController@create")->name("create");
                Route::get("/{token}", "LimiteLimiteController@show")->name("show");
                Route::get("/{token?}/join", "LimiteLimiteController@join")->name("join");
                Route::post("/{token}/join", "LimiteLimiteController@joinRequest")->name("join-request");

            });

    });

resources/views/layouts/footer.blade.php
<!-- Footer -->
<footer class="footer mt-4 pt-4 bg-secondary">

    <!-- Upper Footer -->
    <div class="container text-center">
        <div class="row">

            <!-- Footer Text -->
            <div class="col-12 col-md-6 text-left">
                <h5 class="text-uppercase">{{ app_name() }}</h5>
                <p>{{ trans("strings.created_by") }} <a href="https://twitter.com/AddranorDev" target="_blank">Adrannor</a> {{ trans("strings.and") }} <a href="https://twitter.com/VanilorDev" target="_blank">Vanilor</a></p>
            </div>

            <!-- Links -->
            <div class="col-6 col-md-3">
                <h5 class="text-uppercase">Ressources</h5>
                <ul class="list-unstyled">
                    <li><a href="https://cardmanager.vanilor.info">CardManager</a></li>
                </ul>
            </div>

            <!-- Links -->
            <div class="col-6 col-md-3">
                <h5 class="text-uppercase">Contact</h5>
                <ul class="list-unstyled">
                    <li><a href="https://gitlab.com/Vanilor/card-against-humanity-furfinement/-/issues">{{ trans("app.bug_report") }}</a></li>
                    <li>Discord: Vanilor#9180</li>
                </ul>
            </div>

        </div>
    </div>

    <hr class="m-0">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
        <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
    </div>

</footer>

resources/views/layouts/head.blade.php
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="author" content="Addranor, Vanilor">
<meta name="csrf-token" content="{{ csrf_token() }}">

<link rel="shortcut icon" href="{{ asset("favicon.png")}}" type="image/png">

<!-- Online CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.4.1/yeti/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.4.1/darkly/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">

<!-- Local CSS -->
<link rel="stylesheet" href="{{ asset("css/app.css") }}">
<link rel="stylesheet" href="{{ asset("css/light.css")}}">
<link rel="stylesheet" href="{{ asset("css/dark.css")}}">
<link rel="stylesheet" href="{{ asset("css/debug.css")}}">

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="fr">

    <head>

        @hasSection("title")
            <title>@yield("title") • {{ app_name() }}</title>
        @else
            <title>{{ app_name() }}</title>
        @endif

        @include("layouts.head")
        @yield("styles")

    </head>

    <body>

        <!-- Body Container -->
        <div class="content">
            @include("layouts.nav-top")

            <!-- Page Content -->
            <div @hasSection("container") class="@yield("container")" @else class="container" @endif">

                @yield("content")

            </div>
        </div>

        @include("layouts.footer")
        @include("layouts.scripts")
        @include("layouts.notification")
        @yield("scripts")
    </body>

</html>

resources/views/layouts/nav-top.blade.php
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark justify-content-between">
    <div class="container-fluid">

        <a class="navbar-brand d-none d-sm-block" href="#"><img src="{{ asset("images/logo.png") }}" alt="{{ app_name() }}"></a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">

            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" href="{{ route("limite-limite.create") }}">Créer une partie</a></li>
                <li class="nav-item"><a class="nav-link" href="{{route("limite-limite.home")}}">Liste des parties</a></li>
            </ul>

            <ul class="navbar-nav">
                <li class="dropdown">
                    <a href="" onclick="animateElement('login_menu', 'fadeInLeft')" id="login_button"
                       class="dropdown-toggle nav-link" data-toggle="dropdown" title="User" aria-expanded="true">
                        Se connecter
                    </a>
                    <div id="login_menu" class="dropdown-menu dropdown-menu-right fast">

                        <!-- if LOGGED_IN -> HIDE THIS -->
                        <!-- <h6 class="dropdown-header text-center">Gestion de compte</h6>

                    <div class="img-container"><img src="http://placehold.it/100x100" alt=""></div>
                    <h6 class="text-center mx-3 text-light">Nom d'utilisateur</h6>
                    <h6 class="text-center mx-3 text-light">Adresse@Mail</h6>
                    <div class="dropdown-divider"></div>

                    <a class="dropdown-item px-3 pt-2" href="#"><i class="fas c-fas fa-user-circle"></i> Profil</a>
                    <a class="dropdown-item px-3 pt-2" href="#"><i class="fas c-fas fa-window-restore"></i> Decks favoris</a>
                    <div class="dropdown-divider"></div>

                    <a class="dropdown-item px-3 pt-2" href="#"><i class="fas c-fas fa-power-off"></i> Déconnexion</a> -->
                        <!-- endif -->

                        <!-- if LOGGED_IN -> SHOW THIS -->
                        <h6 class="dropdown-header text-center">Connexion</h6>
                        <div class="dropdown-divider mb-3"></div>

                        <form class="px-3">
                            <div class="form-group">
                                <label class="text-muted" for="usernameInput">Nom d'utilisateur</label>
                                <input type="text" class="form-control" id="usernameInput" placeholder="Username">
                            </div>
                            <div class="form-group">
                                <label class="text-muted" for="passwordInput">Mot de Passe</label>
                                <input type="password" class="form-control" id="passwordInput" placeholder="Password">
                            </div>

                            <fieldset class="form-group">
                                <div class="form-check text-muted">
                                    <label class="form-check-label">
                                        <input class="form-check-input" type="checkbox" value="" checked="">
                                        Se souvenir de moi ?
                                    </label>
                                </div>
                            </fieldset>

                            <div class="form-group">
                                <input type="button" class="btn btn-block btn-primary mt-1" value="Connexion">
                            </div>
                        </form>

                        <div class="text-center w-100">
                            <div class="badge font-weight-light">
                                <a class="text-muted" href="#">Mot de passe oublié ?</a>
                                <span class="text-muted">-</span>
                                <a class="text-muted" href="#">Créer un compte</a>
                            </div>
                        </div>
                        <!-- endif -->

                    </div>
                </li>
            </ul>

        </div>

    </div>
</nav>

resources/views/layouts/notification.blade.php
<script type="text/javascript">
    @foreach (session('flash_notification', collect())->toArray() as $message)

        notify("{{ $message['level'] }}",
                @if($message['level'] === "danger") 'fas fa-times', @elseif($message['level'] === "success") 'fas fa-check', @elseif($message["level"] === "info") 'fas fa-info-circle', @else 'fas fa-exclamation-triangle', @endif
                "{{ $message['message'] }}");

    @endforeach
</script>

@php(session()->forget('flash_notification'))

resources/views/layouts/scripts.blade.php
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{{ asset('js/plugins/bootstrap-notify.min.js') }}"></script>
<script type="text/javascript" src="https://kit.fontawesome.com/4b27d49847.js" crossorigin="anonymous"></script>
<script src="{{ asset("js/app.js") }}"></script>

<script type="text/javascript">
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
</script>